import { sql } from 'drizzle-orm';
import { boolean, check, date, doublePrecision, index, integer, jsonb, pgEnum, pgTable, primaryKey, text, timestamp, uniqueIndex, vector } from 'drizzle-orm/pg-core';

export const entityType = pgEnum('entity_type', ['person','company','institution','technology','product','model','dataset','standard_protocol','paper','event']);
export const signalType = pgEnum('signal_type', ['research','product','funding','acquisition','hiring','policy','technology','market','people','open_source','security','patent','partnership','regulation','supply_chain']);
export const signalStatus = pgEnum('signal_status', ['inbox','reviewed','accepted','rejected','archived']);
export const sourceType = pgEnum('source_type', ['website','rss','paper','company_blog','research_lab','news_media','newsletter','github','social','regulator','patent_database']);
export const topicStatus = pgEnum('topic_status', ['watching','active','strategic','archived']);
export const trend = pgEnum('trend', ['rapid_growth','growth','stable','decline','rapid_decline']);
export const maturity = pgEnum('maturity', ['research','early','emerging','growth','mature']);
export const strategicValue = pgEnum('strategic_value', ['low','medium','high','critical']);
export const radarDomain = pgEnum('radar_domain', ['artificial_intelligence','infrastructure','security','robotics']);

export const topics = pgTable('topics', { id: text('id').primaryKey(), title: text('title').notNull(), parentId: text('parent_id'), status: topicStatus('status').notNull().default('watching'), metadata: jsonb('metadata').notNull().default({}) });
export const entities = pgTable('entities', { id: text('id').primaryKey(), type: entityType('type').notNull(), name: text('name').notNull(), status: text('status').notNull().default('active'), aliases: text('aliases').array().notNull().default(sql`ARRAY[]::text[]`), metadata: jsonb('metadata').notNull().default({}), createdAt: timestamp('created_at',{withTimezone:true}).notNull().defaultNow(), updatedAt: timestamp('updated_at',{withTimezone:true}).notNull().defaultNow() }, (t) => [index('entities_type_idx').on(t.type), index('entities_name_idx').on(t.name)]);
export const sources = pgTable('sources', { id: text('id').primaryKey(), name: text('name').notNull(), type: sourceType('type').notNull(), url: text('url'), trustScore: integer('trust_score').notNull(), active: boolean('active').notNull().default(true), allowedHosts: text('allowed_hosts').array().notNull() }, (t) => [check('sources_trust_score_ck', sql`${t.trustScore} between 0 and 100`), check('sources_allowed_hosts_ck', sql`cardinality(${t.allowedHosts}) > 0`)]);
export const signals = pgTable('signals', { id: text('id').primaryKey(), title: text('title').notNull(), type: signalType('type').notNull(), status: signalStatus('status').notNull().default('inbox'), occurredAt: timestamp('occurred_at',{withTimezone:true}).notNull(), capturedAt: timestamp('captured_at',{withTimezone:true}).notNull().defaultNow(), sourceId: text('source_id').notNull().references(()=>sources.id), sourceUrl: text('source_url').notNull(), summary: text('summary').notNull(), importance: integer('importance').notNull(), strength: integer('strength').notNull(), confidence: doublePrecision('confidence').notNull(), novelty: doublePrecision('novelty').notNull(), metadata: jsonb('metadata').notNull().default({}) }, (t) => [index('signals_occurred_idx').on(t.occurredAt), index('signals_status_idx').on(t.status), check('signals_source_url_https_ck', sql`${t.sourceUrl} ~ '^https://'`), check('signals_importance_ck', sql`${t.importance} between 1 and 5`), check('signals_strength_ck', sql`${t.strength} between 1 and 5`), check('signals_confidence_ck', sql`${t.confidence} between 0 and 1`), check('signals_novelty_ck', sql`${t.novelty} between 0 and 1`)]);
export const entityTopics = pgTable('entity_topics', { entityId: text('entity_id').notNull().references(()=>entities.id,{onDelete:'cascade'}), topicId: text('topic_id').notNull().references(()=>topics.id,{onDelete:'cascade'}) }, (t)=>[primaryKey({columns:[t.entityId,t.topicId]})]);
export const signalTopics = pgTable('signal_topics', { signalId: text('signal_id').notNull().references(()=>signals.id,{onDelete:'cascade'}), topicId: text('topic_id').notNull().references(()=>topics.id,{onDelete:'cascade'}) }, (t)=>[primaryKey({columns:[t.signalId,t.topicId]})]);
export const signalEntities = pgTable('signal_entities', { signalId: text('signal_id').notNull().references(()=>signals.id,{onDelete:'cascade'}), entityId: text('entity_id').notNull().references(()=>entities.id,{onDelete:'cascade'}) }, (t)=>[primaryKey({columns:[t.signalId,t.entityId]})]);
export const relations = pgTable('relations', { id: text('id').primaryKey(), sourceId: text('source_id').notNull().references(()=>entities.id), relationType: text('relation_type').notNull(), targetId: text('target_id').notNull().references(()=>entities.id), confidence: doublePrecision('confidence').notNull().default(1), validFrom: date('valid_from'), validTo: date('valid_to'), sourceRefs: text('source_refs').array().notNull().default(sql`ARRAY[]::text[]`), metadata: jsonb('metadata').notNull().default({}) }, (t)=>[index('relations_source_idx').on(t.sourceId), index('relations_target_idx').on(t.targetId), check('relations_confidence_ck', sql`${t.confidence} between 0 and 1`)]);
export const radarSnapshots = pgTable('radar_snapshots', { id: text('id').primaryKey(), topicId: text('topic_id').notNull().references(()=>topics.id), snapshotDate: date('snapshot_date').notNull(), domain: radarDomain('domain').notNull(), attention: integer('attention').notNull(), trend: trend('trend').notNull(), maturity: maturity('maturity').notNull(), strategicValue: strategicValue('strategic_value').notNull(), confidence: doublePrecision('confidence').notNull(), reasoning: text('reasoning').notNull() }, (t)=>[uniqueIndex('radar_topic_date_uq').on(t.topicId,t.snapshotDate), check('radar_attention_ck', sql`${t.attention} between 0 and 100`), check('radar_confidence_ck', sql`${t.confidence} between 0 and 1`), check('radar_reasoning_ck', sql`length(trim(${t.reasoning})) > 0`)]);
export const radarSnapshotSignals = pgTable('radar_snapshot_signals', { snapshotId: text('snapshot_id').notNull().references(()=>radarSnapshots.id,{onDelete:'cascade'}), signalId: text('signal_id').notNull().references(()=>signals.id), position: integer('position').notNull() }, (t)=>[primaryKey({columns:[t.snapshotId,t.signalId]}), uniqueIndex('radar_snapshot_signal_position_uq').on(t.snapshotId,t.position), index('radar_snapshot_signals_signal_idx').on(t.signalId), check('radar_snapshot_signal_position_ck', sql`${t.position} >= 0`)]);
export const contentRegistry = pgTable('content_registry', { id: text('id').primaryKey(), contentType: text('content_type').notNull(), path: text('path').notNull(), status: text('status').notNull(), publishedAt: timestamp('published_at',{withTimezone:true}), updatedAt: timestamp('updated_at',{withTimezone:true}).notNull().defaultNow() }, (t)=>[uniqueIndex('content_path_uq').on(t.path)]);
export const searchDocuments = pgTable('search_documents', { id: text('id').primaryKey(), sourceId: text('source_id').notNull(), sourceType: text('source_type').notNull(), title: text('title').notNull(), body: text('body').notNull(), importance: integer('importance').notNull().default(1), documentDate: date('document_date'), topics: jsonb('topics').notNull().default([]), entities: jsonb('entities').notNull().default([]), embedding: vector('embedding',{dimensions:1536}) }, (t)=>[index('search_source_idx').on(t.sourceId)]);
