import { sql } from 'drizzle-orm';
import {
  bigint,
  check,
  date,
  index,
  integer,
  jsonb,
  pgTable,
  text,
  timestamp,
  uniqueIndex,
  uuid,
} from 'drizzle-orm/pg-core';

export const signalGenerationRuns = pgTable(
  'signal_generation_runs',
  {
    id: uuid('id').primaryKey(),
    ownerId: text('owner_id').notNull(),
    batchId: uuid('batch_id').notNull(),
    itemId: uuid('item_id').notNull(),
    sourceFence: integer('source_fence').notNull(),
    sourceHash: text('source_hash').notNull(),
    profileId: uuid('profile_id').notNull(),
    profileRevision: integer('profile_revision').notNull(),
    generationVersion: text('generation_version').notNull(),
    fingerprint: text('fingerprint').notNull(),
    snapshot: jsonb('snapshot').notNull(),
    configuration: jsonb('configuration').notNull(),
    status: text('status')
      .notNull()
      .default(sql`'pending'`),
    leaseToken: uuid('lease_token'),
    leaseUntil: timestamp('lease_until', { withTimezone: true }),
    budgetDay: date('budget_day'),
    reservedMicrousd: bigint('reserved_microusd', { mode: 'bigint' }).notNull().default(0n),
    chargedMicrousd: bigint('charged_microusd', { mode: 'bigint' }).notNull().default(0n),
    result: jsonb('result'),
    errorCode: text('error_code'),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    finishedAt: timestamp('finished_at', { withTimezone: true }),
  },
  (t) => [
    check('signal_generation_source_fence_ck', sql`${t.sourceFence} > 0`),
    check('signal_generation_profile_revision_ck', sql`${t.profileRevision} > 0`),
    check('signal_generation_source_hash_ck', sql`${t.sourceHash} ~ '^[a-f0-9]{64}$'`),
    check('signal_generation_fingerprint_ck', sql`${t.fingerprint} ~ '^[a-f0-9]{64}$'`),
    check('signal_generation_snapshot_ck', sql`jsonb_typeof(${t.snapshot}) = 'object'`),
    check('signal_generation_configuration_ck', sql`jsonb_typeof(${t.configuration}) = 'object'`),
    check(
      'signal_generation_status_ck',
      sql`${t.status} IN ('pending','running','completed','failed','unknown','cancelled')`,
    ),
    check('signal_generation_reserved_ck', sql`${t.reservedMicrousd} >= 0`),
    check('signal_generation_charged_ck', sql`${t.chargedMicrousd} >= 0`),
    check(
      'signal_generation_result_ck',
      sql`${t.result} IS NULL OR (jsonb_typeof(${t.result}) = 'object' AND ${t.result}->>'classification' IS NOT DISTINCT FROM 'private')`,
    ),
    uniqueIndex('signal_generation_source_profile_idx').on(
      t.ownerId,
      t.itemId,
      t.sourceFence,
      t.sourceHash,
      t.profileId,
      t.profileRevision,
      t.generationVersion,
    ),
    index('signal_generation_owner_created_idx').on(t.ownerId, t.createdAt),
    index('signal_generation_budget_day_idx').on(t.budgetDay),
    index('signal_generation_batch_idx').on(t.batchId),
  ],
);
